/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type SepaElvTransactionInfo = {
    /**
     * Value of tag E1.DF8206 from NEXO config.
     */
    receiptFormat?: string;
    /**
     * Value of tag E6.DF8211 or E6.DF8212 (Online or Offline TX printout).
     */
    extAppLabel?: string;
    /**
     * Value of tag E6.DF8214 info form NEXO config.
     */
    preNotification?: string;
    /**
     * Value of tag E6.DF8215 info from NEXO config.
     */
    mandate?: string;
    /**
     * Value of tag E6.DF8216 info from NEXO config.
     */
    creditorId?: string;
    /**
     * Generated by SPA according to ELV – TBD: use Trace number instead of receipt number.
     */
    mandateId?: string;
    /**
     * Received in ICC related data from IPG (tag 5F53).
     */
    iban?: string;
    /**
     * Defines if the corresponding SEPA ELV TX was forced by the merchant (override defined limit)
     */
    isMerchantForced?: boolean;
};

