/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type VoidReasonDetails = {
    /**
     * Transaction Error byte in hex
     */
    txError?: string;
    /**
     * Detailed Reason code
     */
    voidReasonCode?: VoidReasonDetails.voidReasonCode;
    /**
     * More detailed reason for voiding the transaction
     */
    description?: string;
    /**
     * enumeration for More detailed reason for voiding the transaction
     */
    descriptionEnum?: string;
    /**
     * Pay Failure Message
     */
    payFailureMessage?: string;
};

export namespace VoidReasonDetails {

    /**
     * Detailed Reason code
     */
    export enum voidReasonCode {
        CANCEL_PAYMENT_ADJUST = 'CANCEL_PAYMENT_ADJUST',
        BREAK_RESET = 'BREAK_RESET',
        CANCEL = 'CANCEL',
        AUTH_FAILED = 'AUTH_FAILED',
        NETWORK_FAILED = 'NETWORK_FAILED',
        NON_OK_RESULT_CODE_RETURNED_FROM_VERIFY_CVM = 'NON_OK_RESULT_CODE_RETURNED_FROM_VERIFY_CVM',
        PARTIAL_AUTH_NOT_ALLOWED = 'PARTIAL_AUTH_NOT_ALLOWED',
        PARTIAL_AUTH_CANCELLED = 'PARTIAL_AUTH_CANCELLED',
        QUICK_CHIP_DECLINE = 'QUICK_CHIP_DECLINE',
        KERNEL_DECLINE = 'KERNEL_DECLINE',
        NON_OK_RESULT_CODE_FROM_FORCE_ACCEPT = 'NON_OK_RESULT_CODE_FROM_FORCE_ACCEPT',
        MERCHANT_CANCELLED_THE_FORCE_ACCEPTANCE = 'MERCHANT_CANCELLED_THE_FORCE_ACCEPTANCE',
        CARD_READER_ERROR = 'CARD_READER_ERROR',
        UNKNOWN_EXCEPTION = 'UNKNOWN_EXCEPTION',
        ERROR_EVENT = 'ERROR_EVENT',
        KERNEL_EXCEPTION = 'KERNEL_EXCEPTION',
        FATAL_EXCEPTION = 'FATAL_EXCEPTION',
        CARD_CHECK_FAILED_FOR_REVERSAL = 'CARD_CHECK_FAILED_FOR_REVERSAL',
        MANUAL_ENTRY_NOT_ALLOWED = 'MANUAL_ENTRY_NOT_ALLOWED',
        MANUAL_ENTRY_NOT_ALLOWED_FOR_CARD = 'MANUAL_ENTRY_NOT_ALLOWED_FOR_CARD',
        SWIPE_CARD_CHECK_FAILED_FOR_REVERSAL = 'SWIPE_CARD_CHECK_FAILED_FOR_REVERSAL',
        OFFLINE_AUTH_FAILED = 'OFFLINE_AUTH_FAILED',
        TXN_STATUS_DECLINED = 'TXN_STATUS_DECLINED',
        COMPLETION_DEVICE = 'COMPLETION_DEVICE',
        NON_OK_RESULT_CODE_FROM_DUPLICATE_CHECK = 'NON_OK_RESULT_CODE_FROM_DUPLICATE_CHECK',
        MERCHANT_CANCELLED_THE_DUPLICATE_CHECK = 'MERCHANT_CANCELLED_THE_DUPLICATE_CHECK',
        NON_OK_RESULT_CODE_RETURNED_FROM_OFFLINE_SCREEN = 'NON_OK_RESULT_CODE_RETURNED_FROM_OFFLINE_SCREEN',
        MERCHANT_CANCELLED_OFFLINE_PAYMENT = 'MERCHANT_CANCELLED_OFFLINE_PAYMENT',
        OFFLINE_AUTH_FAILED_ON_CARD_PRESENT_REVERSAL = 'OFFLINE_AUTH_FAILED_ON_CARD_PRESENT_REVERSAL',
        QUICK_CHIP_TIME_OUT = 'QUICK_CHIP_TIME_OUT',
        HANDLE_PAY_STATE = 'HANDLE_PAY_STATE',
        HANDLE_CONTACT_REQUIRED = 'HANDLE_CONTACT_REQUIRED',
        FINALIZE = 'FINALIZE',
        HANDLE_CARD_DECLINED_TXN_STATUS = 'HANDLE_CARD_DECLINED_TXN_STATUS',
        MERCHANT_REASON = 'MERCHANT_REASON',
    }


}

